DALESURBAN – uDALES
DALESURBAN Program
65 statements
Source File
Uses
modmpi
modglobal
modstartup
modsave
modboundary
modthermodynamics
modsubgrid
modforces
modpois
modibm
initfac
modEB
modchecksim
modstat_nc
modfielddump
modstatsdump
Calls
Contents
Source Code
DALESURBAN
Source Code
program DALESURBAN      !Version 48
!!----------------------------------------------------------------
!!     0.0    USE STATEMENTS FOR CORE MODULES
!!----------------------------------------------------------------
  use modmpi,            only : myid, initmpi
  use modglobal,         only : rk3step,timeleft,ib,jb,kb,ke
  use modstartup,        only : startup,exitmodules
  use modsave,           only : writerestartfiles
  use modboundary,       only : boundary, grwdamp,tqaver
  use modthermodynamics, only : thermodynamics
!  use modsurface,        only : surface
  use modsubgrid,        only : subgrid
  use modforces,         only : forces,coriolis,lstend,fixuinf1,fixuinf2,fixthetainf,nudge, masscorr
  use modpois,           only : poisson
  use modibm,            only : createwalls,ibmwallfun,ibmnorm,nearwall,bottom
  use initfac,           only : readfacetfiles
  use modEB,             only : initEB,EB
!----------------------------------------------------------------
!     0.1     USE STATEMENTS FOR ADDONS STATISTICAL ROUTINES
!----------------------------------------------------------------
  use modchecksim,     only : initchecksim, checksim
  use modstat_nc,      only : initstat_nc
  use modfielddump,    only : initfielddump, fielddump,exitfielddump
  use modstatsdump,    only : initstatsdump,statsdump,exitstatsdump    !tg3315
  !use modbudget,       only : initbudget, budgetstat, exitbudget
  implicit none
!----------------------------------------------------------------
!     1      READ NAMELISTS,INITIALISE GRID, CONSTANTS AND FIELDS
!----------------------------------------------------------------
  call initmpi
  write(*,*) "done initmpi"
  call startup
  write(*,*) "done startup"
!---------------------------------------------------------
!      2     INITIALIZE STATISTICAL ROUTINES AND ADD-ONS
!---------------------------------------------------------
  call initchecksim
  call initstat_nc
  call initfielddump
  call initstatsdump !tg3315
  call readfacetfiles
  call initEB
  write(*,*) "done init stuff"
  write(6,*) 'Determine immersed walls'
  call createwalls    ! determine walls/blocks
 ! call nearwall       ! determine minimum distance and corresponding shear components, ils13 10.07.17, commented, not functional at the moment, not needed for vreman but for smag., fix in modibm
  write(6,*) 'Finished determining immersed walls'
  call boundary  !ils13 22.06.2017 inserted boundary here to get values at ghost cells before iteration starts
!  not necessary but abates the fact that temp field is randomised by randomisation of just velocity fields
!  (because advection at start of time loop without being divergence free)
!  call poisson
!------------------------------------------------------
!   3.0   MAIN TIME LOOP
!------------------------------------------------------
  write(*,*)'START myid ', myid
  do while ((timeleft>0) .or. (rk3step < 3))
    call tstep_update
!-----------------------------------------------------
!   3.2   ADVECTION AND DIFFUSION
!-----------------------------------------------------
    call advection                ! now also includes predicted pressure gradient term
    call subgrid
!-----------------------------------------------------
!   3.3   THE SURFACE LAYER
!-----------------------------------------------------
    call bottom
!-----------------------------------------------------
!   3.4   REMAINING TERMS
!-----------------------------------------------------
    call coriolis       !remaining terms of ns equation
    call forces         !remaining terms of ns equation
    call lstend         !large scale forcings
    call nudge          ! nudge top cells of fields to enforce steady-state
    call ibmwallfun     ! immersed boundary forcing: only shear forces.
    call masscorr       ! correct pred. velocity pup to get correct mass flow
    call ibmnorm        ! immersed boundary forcing: set normal velocities to zero
    call EB
    call scalsource     ! adds continuous forces in specified region of domain
!------------------------------------------------------
!   3.4   EXECUTE ADD ONS
!------------------------------------------------------
    call fixuinf2
    call fixuinf1
!-----------------------------------------------------------------------
!   3.5  PRESSURE FLUCTUATIONS, TIME INTEGRATION AND BOUNDARY CONDITIONS
!-----------------------------------------------------------------------
    call grwdamp        !damping at top of the model
    call poisson
    call tstep_integrate
    call boundary
    call fixthetainf
!-----------------------------------------------------
!   3.6   LIQUID WATER CONTENT AND DIAGNOSTIC FIELDS
!-----------------------------------------------------
    call thermodynamics
!-----------------------------------------------------
!   3.7  WRITE RESTARTFILES AND DO STATISTICS
!------------------------------------------------------
    call checksim
   ! call writedatafiles   ! write data files for later analysis
    call writerestartfiles
    call fielddump
    call statsdump        ! tg3315
  end do
!-------------------------------------------------------
!             END OF TIME LOOP
!-------------------------------------------------------
!--------------------------------------------------------
!    4    FINALIZE ADD ONS AND THE MAIN PROGRAM
!-------------------------------------------------------
  call exitfielddump
  call exitstatsdump     !tg3315
  call exitmodules
end program DALESURBAN
Call graph
dalesurban calls ibmnorm, coriolis, tstep_update, initeb, initchecksim, lstend, fielddump, readfacetfiles, eb, createwalls, thermodynamics, startup, initstat_nc, fixthetainf, scalsource, bottom, exitfielddump, boundary, poisson, fixuinf1, exitmodules, checksim, fixuinf2, grwdamp, tstep_integrate, exitstatsdump, masscorr, ibmwallfun, nudge, advection, initstatsdump, writerestartfiles, statsdump, forces, subgrid, initmpi, initfielddump
tstep_update calls mpi_allreduce
initeb calls define_nc, writestat_dims_nc, matinv4, gaussji, open_nc
initchecksim calls mpi_bcast
fielddump calls writestat_nc
readfacetfiles calls nf90_open, nf90_get_var, mpi_bcast, nf90_inq_varid, qsat
eb calls calclw, matinv4, writestat_1d_nc, intqh, writestat_nc, mpi_bcast, updategr, writestat_2d_nc, gaussji
thermodynamics calls diagfld, thermo, calthv, calc_halflev
startup calls calcfluidvolumes, readinitfiles, initglobal, initpois, initfields, createscals, mpi_bcast, initdriver, initboundary, initsubgrid, checkinitvalues, initinlet, createmasks, initthermodynamics
bottom calls wfmneutral, wfuno
boundary calls valuetop, ioqi, scalrec, inlettop, iohi, drivergen, inletgennotemp, fluxtopscal, cyclichi, iolet, scalsirane, cyclicsj, cyclichj, cyclicmi, cyclicqj, valuetopscal, cyclicsi, inletgen, cyclicmj, cyclicqi, iosi, fluxtop
poisson calls poisr, solmpj, fillps, tderive
fixuinf1 calls detfreestream
exitmodules calls exitinlet, exitpois, exitfields, exitmpi, exitglobal, exitsubgrid, exitthermodynamics
checksim calls calccourant, chkdiv, calcdiffnr
fixuinf2 calls detfreestream
tstep_integrate calls 13, chem
masscorr calls mpi_bcast
ibmwallfun calls ywallfunmin, xwallfun, zwallfun, ywallfunplus
advection calls advecc_kappa, advecv_2nd, advecc_2nd, advecu_2nd, advecw_2nd
initstatsdump calls define_nc, writestat_dims_nc, mpi_bcast, open_nc
statsdump calls writestat_1d_nc, writestat_nc, ekh, ekm, tkestatsdump
subgrid calls diffw, diffv, closure, diffu
initmpi calls mpi_wtime, mpi_cart_shift, mpi_comm_rank, mpi_init, mpi_dims_create, mpi_comm_size, mpi_cart_create
initfielddump calls define_nc, writestat_dims_nc, mpi_bcast, open_nc
calccourant calls mpi_allreduce
calcfluidvolumes calls fluidvolume, uoutletarea, voutletarea
advecc_kappa calls rlim
define_nc calls nf90_inq_varid, nf90_redef, nf90_def_var, nf90_put_att, nf90_enddef, nchandle_error, nf90_inq_dimid
poisr calls vrfftb, blktri, vrfftf, barrou, vrffti, all_all_j2, float
inlettop calls slabsumi
readinitfiles calls thermodynamics, boundary, drivergen, mpi_bcast, calc_halflev, readrestartfiles, randomnize, readdriverfile, slabsum, readinletfile
writestat_dims_nc calls nf90_inq_varid, nf90_inquire_dimension, nf90_put_var
initglobal calls mpi_bcast, float
ywallfunmin calls ywallscalarmin
diagfld calls fromztop
detfreestream calls mpi_allreduce
writestat_1d_nc calls nf90_inq_varid, nf90_sync, nf90_put_var
drivergen calls writedriverfile
inletgennotemp calls writerestartfiles, urec, blthicknesst, slabsum, wrec, utav, dispthicknessexp, uinl, momentumthicknessexp, readinletfile, writeinletfile
iolet calls slabsum
writestat_nc calls writestat_1d_nc, writestat_2d_nc, writestat_3d_short_nc, writestat_time_nc, writestat_3d_nc
updategr calls qsat
exitmpi calls mpi_wtime, mpi_comm_free, mpi_finalize
wfuno calls unoh
cyclichj calls excjs
initsubgrid calls subgridnamelist
cyclicqj calls excjs
closure calls closurebc
checkinitvalues calls mpi_bcast, mpi_finalize
chkdiv calls mpi_allreduce
solmpj calls mpi_comm_rank, mpi_comm_size, all_all_j, rffti, rfftf, float, rfftb
initinlet calls urec, trec, tinl, wrec, utav, uinl, readzincoord, winl, ttav
inletgen calls writerestartfiles, urec, blthicknesst, enthalpythickness, slabsum, trec, tinl, wrec, utav, dispthicknessexp, uinl, momentumthicknessexp, readinletfile, writeinletfile, ttav
ywallfunplus calls ywallscalarplus
writestat_2d_nc calls nf90_inq_varid, nf90_sync, nf90_put_var
fillps calls bcpup
cyclicmj calls excjs
tderive calls bcp
tkestatsdump calls excjs
createmasks calls mpi_allreduce, mpi_bcast
open_nc calls nf90_open, nf90_get_var, nf90_inq_varid, nf90_inquire, nf90_def_var, nf90_def_dim, nf90_create, nf90_put_att, nf90_sync, nf90_enddef, nf90_inquire_dimension, nf90_inq_dimid
calcdiffnr calls mpi_allreduce
writestat_3d_short_nc calls nf90_inq_varid, nf90_sync, nf90_put_var
bcpup calls excjs
readrestartfiles calls zinterpolatew1d, zinterpolatet1d, zinterpolate1d, zinterpolate2d
all_all_j calls mpi_alltoall
subgridnamelist calls mpi_bcast
excjs calls mpi_sendrecv
barrou calls mpi_barrier
slabsum calls mpi_allreduce
dispthicknessexp calls utav
readzincoord calls mpi_bcast
all_all_j2 calls barrou, mpi_alltoall
voutletarea calls mpi_bcast
nchandle_error calls nf90_strerror
readinletfile calls excjs, yinterpolate
writestat_time_nc calls nf90_inq_varid, nf90_sync, nf90_put_var
writestat_3d_nc calls nf90_inq_varid, nf90_sync, nf90_put_var
slabsumi calls mpi_allreduce
closurebc calls excjs
bcp calls excj
excj calls mpi_sendrecv